# Generated by Django 5.1.6 on 2025-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
