# Generated by Django 5.1.6 on 2025-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(default='', max_length=64),
        ),
    ]
