# Generated by Django 5.1.6 on 2025-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
