# Generated by Django 5.1.6 on 2025-03-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
