# Generated by Django 5.1.6 on 2025-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_news_news_body_news_news_date_alter_news_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
