# Generated by Django 5.1.6 on 2025-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_products_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=64)),
                ('deal_name', models.CharField(max_length=64)),
                ('deal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deal_stock', models.PositiveIntegerField(default=0)),
                ('deal_category', models.CharField(default='', max_length=64)),
                ('deal_points', models.PositiveIntegerField(default=0)),
                ('deal_description', models.TextField(default='')),
                ('deal_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
