# Generated by Django 5.1.6 on 2025-03-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='deal_price',
            new_name='deal_new_price',
        ),
        migrations.AddField(
            model_name='deals',
            name='deal_original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
