# Generated by Django 5.1.6 on 2025-03-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_deal_price_deals_deal_new_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='deal_name',
            new_name='deal_product_name',
        ),
    ]
