# Generated by Django 5.1.6 on 2025-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_deal_name_deals_deal_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
