# Generated by Django 5.1.6 on 2025-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_products_is_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_on_sale',
        ),
        migrations.AddField(
            model_name='deals',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
